# Minimal Realm boot smoke test
CONFIG_PRINTK=y
CONFIG_EARLY_CONSOLE=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y

CONFIG_MAIN_STACK_SIZE=4096

# Keep the image as small and simple as possible.
CONFIG_NETWORKING=n
CONFIG_NET_IPV4=n
CONFIG_NET_IPV6=n
CONFIG_POSIX_API=n
CONFIG_SMP=n
